include:
  - backend/docker-compose.yml

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "5173"

  # memoir-3167:
  #   build:
  #     context: ./memoir-3167
  #     dockerfile: Dockerfile
  #   expose:
  #     - "8080"
  #   volumes:
  #     - caddy_data:/data

  caddy:
    image: caddy:2
    ports:
      - "8000:80"
      - "8443:8443"
    volumes:
      - ./Caddyfile:/etc/caddyfile
      - caddy_data:/data
      - caddy_config:/config
    command: caddy run --config /etc/caddyfile
    depends_on:
      - frontend
      - backend
      # - memoir-3167

volumes:
  caddy_data:
  caddy_config:
