include:
  - backend/docker-compose.yml

services:
  base:
    image: game/base-img
    build:
      context: ./memoir-3167
      dockerfile: Dockerfile.base

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend_network
    depends_on:
      - base
    expose:
      - "5173"

  memoir-3167:
    build:
      context: ./memoir-3167
      dockerfile: Dockerfile
    depends_on:
      - base
    expose:
      - "6669"
    networks:
      - backend_network

  caddy:
    image: caddy:2
    ports:
      - "8080:80"
      - "8443:8443"
    volumes:
      - ./Caddyfile:/etc/caddyfile
      - caddy_data:/data
      - caddy_config:/config
    command: caddy run --config /etc/caddyfile
    depends_on:
      - frontend
      - go-server
      - memoir-3167
    networks:
      - frontend_network
      - backend_network

networks:
  frontend_network:
    name: frontend_network
    driver: bridge
  backend_network:
    name: backend_network
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
